# Используем базовый образ с Python
FROM python:3.9-slim
# Устанавливаем рабочую директорию в контейнере
WORKDIR /app
# Копируем файл requirements.txt в рабочую директорию
COPY requirements.txt .
# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt
# Копируем все файлы проекта в рабочую директорию
COPY . .
COPY .env .env
# Указываем команду для запуска бота
CMD ["python", "Main.py"]
